language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# coverage preperation
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest
# coverage testing
after_success:
  - coveralls
  
